[workspace]
members = [
    "crates/foundry-infer-cli",
    "crates/foundry-infer-core",
    "crates/foundry-infer-metal",
    "crates/foundry-infer-plan",
    "crates/foundry-infer-runtime",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MPL-2.0"

[workspace.dependencies]
clap = { version = "4.6.7", default-features = false, features = ["std", "derive", "help", "usage", "error-context"] }
foundry-infer-core = { path = "crates/foundry-infer-core", default-features = false }
foundry-infer-plan = { path = "crates/foundry-infer-plan", default-features = false }
foundry-infer-runtime = { path = "crates/foundry-infer-runtime", default-features = false }
serde = { version = "1.0.229", default-features = false, features = ["std", "derive"] }
serde_json = { version = "1.0.151", default-features = false, features = ["std"] }

[workspace.lints.rust]
warnings = "deny"

[workspace.lints.clippy]
uninlined_format_args = "deny"
missing_assert_message = "deny"
self_named_module_files = "deny"
wildcard_imports = "deny"
semicolon_outside_block = "deny"
single_char_lifetime_names = "deny"
str_to_string = "deny"
unwrap_used = "deny"
new_without_default = "allow"
indexing_slicing = "deny"
fallible_impl_from = "deny"
wildcard_enum_match_arm = "deny"
unneeded_field_pattern = "deny"
fn_params_excessive_bools = "deny"
struct_field_names = "allow"
